/*
DocuSign Admin API

An API for an organization administrator to manage organizations, accounts and users

API version: v2.1
Contact: devcenter@docusign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PagingResponseProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagingResponseProperties{}

// PagingResponseProperties 
type PagingResponseProperties struct {
	// The number of items in a result set (page).
	ResultSetSize *int32 `json:"result_set_size,omitempty"`
	// The index position of the first result in this set.
	ResultSetStartPosition *int32 `json:"result_set_start_position,omitempty"`
	// The index position of the last result in this set.
	ResultSetEndPosition *int32 `json:"result_set_end_position,omitempty"`
	// The total number of results.
	TotalSetSize *int32 `json:"total_set_size,omitempty"`
	// A URL to the next set of results. 
	Next *string `json:"next,omitempty"`
	// A URL to the previous set of results. 
	Previous *string `json:"previous,omitempty"`
}

// NewPagingResponseProperties instantiates a new PagingResponseProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagingResponseProperties() *PagingResponseProperties {
	this := PagingResponseProperties{}
	return &this
}

// NewPagingResponsePropertiesWithDefaults instantiates a new PagingResponseProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagingResponsePropertiesWithDefaults() *PagingResponseProperties {
	this := PagingResponseProperties{}
	return &this
}

// GetResultSetSize returns the ResultSetSize field value if set, zero value otherwise.
func (o *PagingResponseProperties) GetResultSetSize() int32 {
	if o == nil || IsNil(o.ResultSetSize) {
		var ret int32
		return ret
	}
	return *o.ResultSetSize
}

// GetResultSetSizeOk returns a tuple with the ResultSetSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingResponseProperties) GetResultSetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.ResultSetSize) {
		return nil, false
	}
	return o.ResultSetSize, true
}

// HasResultSetSize returns a boolean if a field has been set.
func (o *PagingResponseProperties) HasResultSetSize() bool {
	if o != nil && !IsNil(o.ResultSetSize) {
		return true
	}

	return false
}

// SetResultSetSize gets a reference to the given int32 and assigns it to the ResultSetSize field.
func (o *PagingResponseProperties) SetResultSetSize(v int32) {
	o.ResultSetSize = &v
}

// GetResultSetStartPosition returns the ResultSetStartPosition field value if set, zero value otherwise.
func (o *PagingResponseProperties) GetResultSetStartPosition() int32 {
	if o == nil || IsNil(o.ResultSetStartPosition) {
		var ret int32
		return ret
	}
	return *o.ResultSetStartPosition
}

// GetResultSetStartPositionOk returns a tuple with the ResultSetStartPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingResponseProperties) GetResultSetStartPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.ResultSetStartPosition) {
		return nil, false
	}
	return o.ResultSetStartPosition, true
}

// HasResultSetStartPosition returns a boolean if a field has been set.
func (o *PagingResponseProperties) HasResultSetStartPosition() bool {
	if o != nil && !IsNil(o.ResultSetStartPosition) {
		return true
	}

	return false
}

// SetResultSetStartPosition gets a reference to the given int32 and assigns it to the ResultSetStartPosition field.
func (o *PagingResponseProperties) SetResultSetStartPosition(v int32) {
	o.ResultSetStartPosition = &v
}

// GetResultSetEndPosition returns the ResultSetEndPosition field value if set, zero value otherwise.
func (o *PagingResponseProperties) GetResultSetEndPosition() int32 {
	if o == nil || IsNil(o.ResultSetEndPosition) {
		var ret int32
		return ret
	}
	return *o.ResultSetEndPosition
}

// GetResultSetEndPositionOk returns a tuple with the ResultSetEndPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingResponseProperties) GetResultSetEndPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.ResultSetEndPosition) {
		return nil, false
	}
	return o.ResultSetEndPosition, true
}

// HasResultSetEndPosition returns a boolean if a field has been set.
func (o *PagingResponseProperties) HasResultSetEndPosition() bool {
	if o != nil && !IsNil(o.ResultSetEndPosition) {
		return true
	}

	return false
}

// SetResultSetEndPosition gets a reference to the given int32 and assigns it to the ResultSetEndPosition field.
func (o *PagingResponseProperties) SetResultSetEndPosition(v int32) {
	o.ResultSetEndPosition = &v
}

// GetTotalSetSize returns the TotalSetSize field value if set, zero value otherwise.
func (o *PagingResponseProperties) GetTotalSetSize() int32 {
	if o == nil || IsNil(o.TotalSetSize) {
		var ret int32
		return ret
	}
	return *o.TotalSetSize
}

// GetTotalSetSizeOk returns a tuple with the TotalSetSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingResponseProperties) GetTotalSetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalSetSize) {
		return nil, false
	}
	return o.TotalSetSize, true
}

// HasTotalSetSize returns a boolean if a field has been set.
func (o *PagingResponseProperties) HasTotalSetSize() bool {
	if o != nil && !IsNil(o.TotalSetSize) {
		return true
	}

	return false
}

// SetTotalSetSize gets a reference to the given int32 and assigns it to the TotalSetSize field.
func (o *PagingResponseProperties) SetTotalSetSize(v int32) {
	o.TotalSetSize = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PagingResponseProperties) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingResponseProperties) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PagingResponseProperties) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PagingResponseProperties) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PagingResponseProperties) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingResponseProperties) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PagingResponseProperties) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PagingResponseProperties) SetPrevious(v string) {
	o.Previous = &v
}

func (o PagingResponseProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagingResponseProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResultSetSize) {
		toSerialize["result_set_size"] = o.ResultSetSize
	}
	if !IsNil(o.ResultSetStartPosition) {
		toSerialize["result_set_start_position"] = o.ResultSetStartPosition
	}
	if !IsNil(o.ResultSetEndPosition) {
		toSerialize["result_set_end_position"] = o.ResultSetEndPosition
	}
	if !IsNil(o.TotalSetSize) {
		toSerialize["total_set_size"] = o.TotalSetSize
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	return toSerialize, nil
}

type NullablePagingResponseProperties struct {
	value *PagingResponseProperties
	isSet bool
}

func (v NullablePagingResponseProperties) Get() *PagingResponseProperties {
	return v.value
}

func (v *NullablePagingResponseProperties) Set(val *PagingResponseProperties) {
	v.value = val
	v.isSet = true
}

func (v NullablePagingResponseProperties) IsSet() bool {
	return v.isSet
}

func (v *NullablePagingResponseProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagingResponseProperties(val *PagingResponseProperties) *NullablePagingResponseProperties {
	return &NullablePagingResponseProperties{value: val, isSet: true}
}

func (v NullablePagingResponseProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagingResponseProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


