/*
DocuSign Admin API

An API for an organization administrator to manage organizations, accounts and users

API version: v2.1
Contact: devcenter@docusign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UsersDrilldownResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersDrilldownResponse{}

// UsersDrilldownResponse Information about a list of users.
type UsersDrilldownResponse struct {
	// A list of users.
	Users []UserDrilldownResponse `json:"users,omitempty"`
}

// NewUsersDrilldownResponse instantiates a new UsersDrilldownResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersDrilldownResponse() *UsersDrilldownResponse {
	this := UsersDrilldownResponse{}
	return &this
}

// NewUsersDrilldownResponseWithDefaults instantiates a new UsersDrilldownResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersDrilldownResponseWithDefaults() *UsersDrilldownResponse {
	this := UsersDrilldownResponse{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *UsersDrilldownResponse) GetUsers() []UserDrilldownResponse {
	if o == nil || IsNil(o.Users) {
		var ret []UserDrilldownResponse
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersDrilldownResponse) GetUsersOk() ([]UserDrilldownResponse, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *UsersDrilldownResponse) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []UserDrilldownResponse and assigns it to the Users field.
func (o *UsersDrilldownResponse) SetUsers(v []UserDrilldownResponse) {
	o.Users = v
}

func (o UsersDrilldownResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersDrilldownResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

type NullableUsersDrilldownResponse struct {
	value *UsersDrilldownResponse
	isSet bool
}

func (v NullableUsersDrilldownResponse) Get() *UsersDrilldownResponse {
	return v.value
}

func (v *NullableUsersDrilldownResponse) Set(val *UsersDrilldownResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersDrilldownResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersDrilldownResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersDrilldownResponse(val *UsersDrilldownResponse) *NullableUsersDrilldownResponse {
	return &NullableUsersDrilldownResponse{value: val, isSet: true}
}

func (v NullableUsersDrilldownResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersDrilldownResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


