openapi: 3.0.1
info:
  contact:
    email: devcenter@docusign.com
    name: DocuSign Developer Center
    url: https://developers.docusign.com
  description: "An API for an organization administrator to manage organizations,\
    \ accounts and users"
  termsOfService: https://www.docusign.com/company/terms-and-conditions/developers
  title: DocuSign Admin API
  version: v2.1
servers:
- url: https://api.docusign.net/Management
tags:
- description: Methods to get a list of identity providers.
  name: IdentityProviders
- description: Methods to get a list of reserved domains.
  name: ReservedDomains
- description: Methods to manage users in an account.
  name: Users
- description: Methods to manage eSignature users in an account.
  name: eSignUserManagement
- description: Methods to manage multi-product users in an account.
  name: MultiProductUserManagement
- description: Methods for exporting a user list.
  name: UserExport
- description: Methods and objects to get account information.
  name: AccountSettingsExport
- description: |-
    Methods to import users.

    To ensure your CSV is properly formatted, use the
    [Sample Bulk Add CSV file](https://admin.docusign.com/static-resources/organization-user-import.csv)
     as a template.

    You can add up to 2,000 users to an account and include up to 50 accounts per import. The maximum number of users per import is 8,000.
  name: UserImport
- description: Methods for working with organizations.
  name: Organization
- description: Methods and objects to update account settings.
  name: AccountSettingsImport
- description: Methods to import users.
  name: SingleAccountUserImport
- description: "Methods to delete user data. After a user is closed, an account or\
    \ organization administrator can use these methods to delete the user's account\
    \ data."
  name: DataDeletion
- description: Methods to clone accounts.
  name: AccountCloning
paths:
  /v2/organizations:
    get:
      description: |-
        Returns a list of organizations that the authenticated user belongs to.

        Note that the DocuSign Admin API only returns JSON, not XML.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `organization_read`.

        This method requires user authentication. It will fail with an [application access token](/docs/admin-api/admin101/application-auth/).
      operationId: Organization_Organization_GetListV2
      security:
      - accessCode:
        - organization_read
      summary: Returns a list of organizations that the authenticated user belongs
        to.
      tags:
      - Organization
      x-ds-methodname: getOrganizations
      x-ds-method: getOrganizations
      x-ds-service: Accounts
      x-ds-in-sdk: true
  /v2/data_redaction/accounts/{accountId}/user:
    post:
      description: "Deletes the data for a single account membership for a specified\
        \ user.\n\nTo call this endpoint: \n* You must be an administrator (or delegated\
        \ administrator) of the specified account.\n* The user must have been closed\
        \ for at least 24 hours.\n\n**Note:** After a user's data is deleted for every\
        \ account to which they belong, their user-level data will automatically be\
        \ deleted.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/):\
        \ `user_data_redact`.\n"
      operationId: DataRedaction_RedactIndividualMembershipData
      security:
      - accessCode:
        - user_data_redact
      summary: Deletes membership data for a user on an account.
      tags:
      - DataDeletion
      x-ds-methodname: redactIndividualMembershipData
      x-ds-method: redactIndividualMembershipData
      x-ds-service: Accounts
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/permissions:
    get:
      description: |+
        Returns the list of permission profiles in an account.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `permission_read`.

      operationId: Account_Accounts_GetPermissionProfilesV2
      security:
      - accessCode:
        - permission_read
      summary: Returns the list of permission profiles in an account.
      tags:
      - eSignUserManagement
      x-ds-methodname: getPermissions
      x-ds-method: getPermissions
      x-ds-service: Accounts
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/groups:
    get:
      description: |
        Returns the list of groups in an account.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `group_read`.
      operationId: Account_Accounts_GetGroupsV2
      security:
      - accessCode:
        - group_read
      summary: Returns the list of groups in an account.
      tags:
      - eSignUserManagement
      x-ds-methodname: getGroups
      x-ds-method: getGroups
      x-ds-service: Accounts
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/exports/user_list:
    get:
      description: |
        Returns a list of pending and completed export requests.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationExport_OrganizationExport_Get
      security:
      - accessCode:
        - user_read
      summary: Returns a list of pending and completed export requests.
      tags:
      - UserExport
      x-ds-methodname: getUserListExports
      x-ds-method: getUserListExports
      x-ds-service: BulkExports
      x-ds-in-sdk: true
    post:
      description: "Create a user list export request.\n\nThis method initiates a\
        \ user list export request. You specify the type of export request as JSON\
        \ in the body of method, like this:\n\n``` json\n{\n\t\"type\": \"organization_memberships_export\"\
        \n}\n```\n\nThe export request type is one of three values:\n\n| Value   \
        \                                   | Description                        \
        \                                                                     |\n\
        | :----------------------------------------- | :------------------------------------------------------------------------------------------------------\
        \ |\n| `organization_memberships_export`          | Every user in every account\
        \ in the organization. Users in multiple accounts will appear more than once.\
        \ |\n| `organization_domain_users_export`         | All users of the reserved\
        \ domains.                                                               \
        \       |\n| `organization_external_memberships_export` | Users whose email\
        \ address domain is *not* linked to the organization.                    \
        \               |\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/):\
        \ `user_read`."
      operationId: OrganizationExport_OrganizationExport_Insert
      security:
      - accessCode:
        - user_read
      summary: Creates a user list export request.
      tags:
      - UserExport
      x-ds-methodname: createUserListExport
      x-ds-method: createUserListExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/exports/account_settings:
    get:
      description: |-
        Returns a list of pending and completed account settings export requests.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.
      operationId: OrganizationExport_OrganizationExport_GetAccountCompare
      security:
      - accessCode:
        - account_read
      summary: Returns a list of pending and completed account settings export request.
      tags:
      - AccountSettingsExport
      x-ds-methodname: getAccountSettingsExports
      x-ds-method: getAccountSettingsExports
      x-ds-service: BulkExports
      x-ds-in-sdk: true
    post:
      description: "Creates a new account settings export request.\n\nTo learn more\
        \ about exporting account settings,\nsee [Account Settings Export][guide-export]\n\
        in the DocuSign Admin Guide.\n\nYou can export settings for up to 40 accounts\
        \ at a time.\n\nSpecify the accounts whose settings you are requesting as\
        \ JSON in the body of the request, like this:\n\n``` json\n{\n  \"accounts\"\
        :\t[\n  \t{ \"account_id\": \"9ca037f4-xxxx-xxxx-xxxx-212e57d4f22e\"},\n \
        \ \t{ \"account_id\": \"624e3e00-xxxx-xxxx-xxxx-43918c520dab\"}\n\n  ]\n}\n\
        ```\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `account_write`.\n\
        \n### Related topics\n\n- [Account Settings import][guide-import] guide\n\
        - [Account Settings Export][guide-export] guide\n\n\n[guide-import]: https://support.docusign.com/s/document-item?bundleId=rrf1583359212854&topicId=nwl1583359167434.html\n\
        [guide-export]: https://support.docusign.com/s/document-item?bundleId=rrf1583359212854&topicId=kfj1583359164049.html"
      operationId: OrganizationExport_OrganizationExport_AccountCompare
      security:
      - accessCode:
        - account_read
      summary: Creates a  new account settings export request.
      tags:
      - AccountSettingsExport
      x-ds-methodname: createAccountSettingsExport
      x-ds-method: createAccountSettingsExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/exports/user_list/{exportId}:
    delete:
      description: |+
        Deletes a single user list export request.
        Use this method to delete pending or completed user export requests.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.

      operationId: OrganizationExport_OrganizationExport_DeleteByExportId
      security:
      - accessCode:
        - user_read
      summary: Deletes a single user list export request.
      tags:
      - UserExport
      x-ds-methodname: deleteUserListExport
      x-ds-method: deleteUserListExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
    get:
      description: |-
        Returns the results for single user list export request.

        Given an export ID, this method returns the results of a single user list export request.
        To get a list of all the export requests, use `getUserListExports`.

        Note that the `metadata_url` property of the response from `createUserListExport` is a read-to-use HTTP GET request to get the status.

        The results are available through a URL that
        you can access through the `results` property of the response.
        For example, to get the URL of the first result you might use
        `results[0].url`

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationExport_OrganizationExport_GetByExportId
      security:
      - accessCode:
        - user_read
      summary: Returns the results for single user list export request.
      tags:
      - UserExport
      x-ds-methodname: getUserListExport
      x-ds-method: getUserListExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/exports/account_settings/{exportId}:
    delete:
      description: |
        Deletes a single account settings export request.
        Any data associated with the request is also deleted.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.
      operationId: OrganizationExport_OrganizationExport_DeleteByAccountSettingsExportId
      security:
      - accessCode:
        - account_read
      summary: Deletes a single account settings export request.
      tags:
      - AccountSettingsExport
      x-ds-methodname: deleteAccountSettingsExport
      x-ds-method: deleteAccountSettingsExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
    get:
      description: |-
        Returns the results for a single account settings export request.

        Given an export ID, this method returns the results of an account settings export request.
        To get a list of all the export requests, use `getAccountSettingsExports`.

        The results are available through a URL that
        you can access through the `results` property of the response.
        For example, to get the URL of first result you might use
        `results[0].url`

        The settings export is formatted like this:

        ``` json
        {
          "accounts": [
            {
              "account_id": "9ca037f4-xxxx-xxxx-xxxx-212e57d4f22e",
              "name": "The Happy Company",
              . . .
            },
            {
              "account_id": "624e3e00-xxxx-xxxx-xxxx-43918c520dab",
              "name": "LoanCo",
              . . .
            }
          ],
          "settings": [
            . . .
            {
              "category": "Signing",
              "name": "SignerCanSignOnMobile",
              "account_values": [
                {
                  "account_id": "9ca037f4-xxxx-xxxx-xxxx-212e57d4f22e",
                  "value": "true",
                  "rights": "editable"
                },
                {
                  "account_id": "624e3e00-xxxx-xxxx-xxxx-43918c520dab",
                  "value": "true",
                  "rights": "editable"
                }
              ]
            },
            . . .
          ]
        }

        ```

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.
      operationId: OrganizationExport_OrganizationExport_GetAccountSettingsExportByExportId
      security:
      - accessCode:
        - account_read
      summary: Returns the results for a single account settings export request.
      tags:
      - AccountSettingsExport
      x-ds-methodname: getAccountSettingsExport
      x-ds-method: getAccountSettingsExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/account_settings:
    get:
      description: |-
        Returns the details and metadata for Bulk Account Settings Import requests in the organization.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.
      operationId: OrganizationImport_OrganizationImportAccountSettings_Get
      security:
      - accessCode:
        - account_read
      summary: Returns the details and metadata for Bulk Account Settings Import requests
        in the organization.
      tags:
      - AccountSettingsImport
      x-ds-methodname: getBulkAccountSettingsImports
      x-ds-method: getBulkAccountSettingsImports
      x-ds-service: BulkImports
      x-ds-in-sdk: true
    post:
      description: |
        Creates a new account settings import request.

        The request for this method consists of
        the contents of a CSV
        file.

        You can export your current settings as a CSV file with
        [AccountSettingsExport: createAccountSettingsExport](/docs/admin-api/reference/bulkoperations/accountsettingsexport/createaccountsettingsexport/)
        and use it as the basis
        of the changes you want to import.


        To learn more about the format
        of a settings CSV file, see
        [Preparing a CSV for account settings import][guide-import]
        in the DocuSign Admin Guide.

        You can import settings for up to 40 accounts at a time.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `account_write`.

        ### Related topics

        - [Account Settings import][guide-import] guide
        - [Account Settings Export][guide-export] guide

        [guide-import]: https://support.docusign.com/s/document-item?bundleId=rrf1583359212854&topicId=nwl1583359167434.html
        [guide-export]: https://support.docusign.com/s/document-item?bundleId=rrf1583359212854&topicId=kfj1583359164049.html
      operationId: OrganizationImport_OrganizationImportAccountSettings_Post
      security:
      - accessCode:
        - account_write
      summary: Creates a new account settings import request.
      tags:
      - AccountSettingsImport
      x-ds-methodname: addBulkAccountSettingsImport
      x-ds-method: addBulkAccountSettingsImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/account_settings/{importId}:
    delete:
      description: |-
        Deletes a single account settings import request.
        Any data associated with the request is also deleted.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `account_write`.
      operationId: OrganizationImport_OrganizationImportAccountSettings_DeleteById
      security:
      - accessCode:
        - account_write
      summary: Deletes a Bulk Account Settings Import request.
      tags:
      - AccountSettingsImport
      x-ds-methodname: deleteBulkAccountSettingsImport
      x-ds-method: deleteBulkAccountSettingsImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
    get:
      description: |
        Returns the details/metadata for a Bulk Account Settings Import request.

        Given an import ID, this method returns the results of an account settings import request.
        To get a list of all the import requests, use `getAccountSettingsImports`.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.
      operationId: OrganizationImport_OrganizationImportAccountSettings_GetById
      security:
      - accessCode:
        - account_read
      summary: Returns the details/metadata for a Bulk Account Settings Import request.
      tags:
      - AccountSettingsImport
      x-ds-methodname: getBulkAccountSettingsImport
      x-ds-method: getBulkAccountSettingsImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/add:
    post:
      description: |
        Creates a request to import *new* users.

        Your CSV import file is made up of a header row with the column headers and a row of user or account data for each user you want to add to an account. Only new users can be imported. Any changes to existing users will be ignored. To make changes to existing users, use [UserImport:updateBulkUserImports][imports].

        To ensure your CSV is properly formatted, use the
        [Sample Bulk Add CSV file](https://admin.docusign.com/static-resources/organization-user-import.csv)
         as a template. The following table describes the columns.



        | Column              | Required | Description                                                                                                                                                                                                                                                                                                                                                                                                         |
        | :------------------ | :------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
        | AccountID           | yes      | The API account ID for the account to which you want you add the user. You can find this ID in the Admin area for the account under **API and Keys.**                                                                                                                                                                                                                                                            |
        | AccountName         |          | The name of the user's account in your organization. The account name must match the account ID provided.                                                                                                                                                                                                                                                                                                           |
        | FirstName           | yes      | The user's first name.                                                                                                                                                                                                                                                                                                                                                                                              |
        | LastName            | yes      | The user's last name.                                                                                                                                                                                                                                                                                                                                                                                               |
        | UserEmail           | yes      | The user's complete email address.                                                                                                                                                                                                                                                                                                                                                                                  |
        | PermissionSet       | yes      | The user's permission set. The PermissionSet value must match an existing permission set for the account. This value is not case sensitive.                                                                                                                                                                                                                                                                         |
        | UserTitle           |          | The user's job title.                                                                                                                                                                                                                                                                                                                                                                                               |
        | CompanyName         |          | The user's company name.                                                                                                                                                                                                                                                                                                                                                                                            |
        | Group               |          | The user's assigned groups. The Group values must match existing Group names for the account. Additional Group columns can be added to the file to add users to more than one group. You do not need to add users to the Everyone group, since all new users are automatically added to that group.                                                                                                                 |
        | AddressLine1        |          | The user's address, first line.                                                                                                                                                                                                                                                                                                                                                                                     |
        | AddressLine2        |          | The user's address, second line.                                                                                                                                                                                                                                                                                                                                                                                    |
        | City                |          | The user's city name.                                                                                                                                                                                                                                                                                                                                                                                               |
        | StateRegionProvince |          | The user's regional location.                                                                                                                                                                                                                                                                                                                                                                                       |
        | PostalCode          |          | The user's postal code.                                                                                                                                                                                                                                                                                                                                                                                             |
        | Phone               |          | The user's phone number.                                                                                                                                                                                                                                                                                                                                                                                            |
        | Language            |          | The user's display language for their DocuSign account. Must be one of: <ul><li>Chinese Simplified: <code>zh_CN</code></li><li>Chinese Traditional: <code>zh_TW</code></li><li>Dutch: <code>nl</code></li><li>English: <code>en</code></li><li>French: <code>fr</code></li><li>German: <code>de</code></li><li>Italian: <code>it</code></li><li>Japanese: <code>ja</code></li><li>Korean: <code>ko</code></li><li>Portuguese: <code>pt</code></li><li>Portuguese Brazil: [...]
        | LoginPolicy         |          | The user's login policy. Valid values include the following: <ul> <li>Column left blank = The user is created with no policy assigned.</li> <li>FedAuthRequired = The user must log in with an Identity Provider.</li> <li>FedAuthBypass = The user may log in with an Identity Provider or their DocuSign username and password.</li> </ul> For more information on login policies, see [Setting User Login Policy](https://support.docusign.com/s/document-item?bundleI[...]
        | AutoActivate        |          | For domain users, new users can be activated automatically for domain accounts using SSO by setting the value to **true.** The user is activated automatically once the import is complete. Memberships activated in this way do not receive an activation email.                                                                                                                                                   |


        You can add up to 2,000 users to an account and include up to 50 accounts per import. The maximum number of users per import is 8,000.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.


        [imports]: /docs/admin-api/reference/bulkoperations/userimport/updatebulkuserimports/
      operationId: OrganizationImport_OrganizationImportUsers_Insert
      security:
      - accessCode:
        - user_write
      summary: Creates a request to import new users into an account.
      tags:
      - UserImport
      x-ds-methodname: addBulkUserImport
      x-ds-method: addBulkUserImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/imports/bulk_users/add:
    post:
      description: |
        Import request for adding a user to a single account within the organization.
        This method lets you upload user information without requiring an AccountId column.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationImport_OrganizationImportSingleAccountUsers_Insert
      security:
      - accessCode:
        - user_write
      summary: Import request for adding a user to a single account within the organization.
      tags:
      - SingleAccountUserImport
      x-ds-methodname: createBulkImportSingleAccountAddUsersRequest
      x-ds-method: createBulkImportSingleAccountAddUsersRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/update:
    post:
      description: "Bulk updates information for existing users.\n\nYour CSV import\
        \ file is made up of a header row with the column headers and a row of user\
        \ or account data for each user you want to add to an account. \n\n\n**Update\
        \ limit:** You can update up to 2,000 users on an account and include up to\
        \ 50 accounts per import. The maximum number of updated users per import is\
        \ 8,000.\n\nThis method requires the following HTTP headers:\n\n| Header |\
        \ Value |\n| :--- |  :--- |\n| Content-Type | `text/csv` |\n| Content-Disposition\
        \ |  `filename=filename.csv` |\n\n\n\nTo ensure your CSV is properly formatted,\
        \ use the\n[Sample Bulk Update CSV file](https://admin.docusign.com/static-resources/organization-user-update-import.csv)\n\
        \ as a template. The following table describes the columns.\n\nNote that the\
        \ columns for bulk adding users and bulk update users are slightly different.\n\
        The update CSV file requires an `APIUserName` column, and does not have an\
        \ `AutoActivate` column.\n\n\n\n| Column              | Required | Description\
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                 |\n| :------------------ | :------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\
        \ |\n| AccountID           | yes      | The 32-character API account ID of\
        \ the user's account in your organization. You can find this value in the\
        \ API and Keys section of the Admin area of the account.                 \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                    |\n| AccountName         |          | The name of the\
        \ user's account in your organization. The account name must match the account\
        \ ID provided.                                                           \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                        |\n| FirstName           | yes      | The user's\
        \ first name.                                                            \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                  |\n| LastName            | yes      | The\
        \ user's last name.                                                      \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                         |\n| UserEmail           | yes \
        \     | The user's complete email address.                               \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                   |\n| PermissionSet   \
        \    | yes      | The user's permission set. The PermissionSet value must\
        \ match an existing permission set for the account. This value is not case\
        \ sensitive.                                                             \
        \                                                                        \
        \                                                                        \
        \                                                            |\n| UserTitle\
        \           |          | The user's job title.                           \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                    |\n|\
        \ CompanyName         |          | The user's company name.              \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \      |\n| Group               |          | The user's assigned groups. The\
        \ Group values must match existing Group names for the account. Additional\
        \ Group columns can be added to the file to add users to more than one group.\
        \ You do not need to add users to the Everyone group, since all new users\
        \ are automatically added to that group.                                 \
        \                                                                        \
        \        |\n| AddressLine1        |          | The user's address, first line.\
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \             |\n| AddressLine2        |          | The user's address, second\
        \ line.                                                                  \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                  |\n| City                |          | The user's city name.\
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                       |\n| StateRegionProvince |          | The user's regional\
        \ location.                                                              \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                         |\n| PostalCode          |          | The user's\
        \ postal code.                                                           \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                  |\n| Phone               |          | The\
        \ user's phone number.                                                   \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                         |\n| Language            |     \
        \     | The user's display language for their DocuSign account. Must be one\
        \ of: <ul><li>Chinese Simplified: <code>zh_CN</code></li><li>Chinese Traditional:\
        \ <code>zh_TW</code></li><li>Dutch: <code>nl</code></li><li>English: <code>en</code></li><li>French:\
        \ <code>fr</code></li><li>German: <code>de</code></li><li>Italian: <code>it</code></li><li>Japanese:\
        \ <code>ja</code></li><li>Korean: <code>ko</code></li><li>Portuguese: <code>pt</code></li><li>Portuguese\
        \ Brazil: <code>pt_BR</code></li><li>Russian: <code>ru</code></li><li>Spanish:\
        \ <code>es</code></li></ul>                                              \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \                                                                        \
        \              |\n| LoginPolicy         |          | The user's login policy.\
        \ Valid values include the following: <ul> <li>Column left blank = The user\
        \ is created with no policy assigned.</li> <li>FedAuthRequired = The user\
        \ must log in with an Identity Provider.</li> <li>FedAuthBypass = The user\
        \ may log in with an Identity Provider or their DocuSign username and password.</li>\
        \ </ul> For more information on login policies, see [Setting User Login Policy](https://support.docusign.com/s/document-item?bundleId=rrf1583359212854&topicId=zah1583359147774.html).\
        \ |\n| AutoActivate        |          | For domain users, new users can be\
        \ activated automatically for domain accounts using SSO by setting the value\
        \ to **true.** The user is activated automatically once the import is complete.\
        \ Memberships activated in this way do not receive an activation email.  \
        \                                                                        \
        \                                                                        \
        \ |\n\n\n\n## Updating user email addresses\n\nChanging a user's email address\
        \ should be done carefully. The user's email address is used to log in to\
        \ DocuSign and receive documents to sign from others.\nOnce changed, existing\
        \ documents that were sent or received:\n\n- Will still appear in the user's\
        \ documents list.\n- Notifications about these documents will be sent to the\
        \ new email address. If someone sends a new document to the old email address:\n\
        - DocuSign will send a notification to the old address.\n- It will not appear\
        \ in the documents list of the account.\n\nThis change of email address will\
        \ be applied to all of the user's account memberships.\n\n[Required authentication\
        \ scopes](/docs/admin-api/admin101/auth/): `user_write`."
      operationId: OrganizationImport_OrganizationImportUsers_Update
      security:
      - accessCode:
        - user_write
      summary: Bulk updates information for existing users.
      tags:
      - UserImport
      x-ds-methodname: updateBulkUserImports
      x-ds-method: updateBulkUserImports
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/imports/bulk_users/update:
    post:
      description: |+
        Import request for updating users for a single account
        within the organization.

        This method lets you upload user information without requiring an `AccountId` column.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.

      operationId: OrganizationImport_OrganizationImportSingleAccountUsers_Update
      security:
      - accessCode:
        - user_write
      summary: |-
        Import request for updating users for a single account
        within the organization.
      tags:
      - SingleAccountUserImport
      x-ds-methodname: createBulkImportSingleAccountUpdateUsersRequest
      x-ds-method: createBulkImportSingleAccountUpdateUsersRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/close:
    post:
      description: |-
        Creates a request to close the accounts of existing users.

        Given a CSV list of users, close their accounts.

        Your CSV import file is made up of a header row with the column headers and a row of user or account data for each user whose account you want to close.

        To ensure your CSV is properly formatted, use the
        [Sample Bulk Update CSV file](https://admin.docusign.com/static-resources/organization-user-update-import.csv)
         as a template. The following table describes the columns.




        | Column              | Required | Description                                                                                                                                                                                                                                                                                                                                                                                                         |
        | :------------------ | :------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
        | AccountID           | yes      | The 32-character API account ID of the user's account in your organization. You can find this value in the API and Keys section of the Admin area of the account.                                                                                                                                                                                                                                                             |
        | AccountName         |          | The name of the user's account in your organization. The account name must match the account ID provided.                                                                                                                                                                                                                                                                                                           |
        | FirstName           | yes      | The user's first name.                                                                                                                                                                                                                                                                                                                                                                                              |
        | LastName            | yes      | The user's last name.                                                                                                                                                                                                                                                                                                                                                                                               |
        | UserEmail           | yes      | The user's complete email address.                                                                                                                                                                                                                                                                                                                                                                                  |
        | PermissionSet       | yes      | The user's permission set. The PermissionSet value must match an existing permission set for the account. This value is not case sensitive.                                                                                                                                                                                                                                                                         |

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationImport_OrganizationImportUsers_Close
      security:
      - accessCode:
        - user_write
      summary: Creates a request to close the accounts of existing users.
      tags:
      - UserImport
      x-ds-methodname: closeBulkUserImportRequest
      x-ds-method: closeBulkUserImportRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/close_external:
    post:
      description: |
        Closes external memberships.

        External memberships are users who have an email address at a verified domain but do not belong to the organization.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationImport_OrganizationImportUsers_CloseExternal
      security:
      - accessCode:
        - user_write
      summary: Closes external memberships.
      tags:
      - UserImport
      x-ds-methodname: closeBulkExternalUserImportRequest
      x-ds-method: closeBulkExternalUserImportRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users:
    get:
      description: |-
        Gets a list of all of the user import requests.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationImport_OrganizationImportUsers_Get
      security:
      - accessCode:
        - user_read
      summary: Gets a list of all of the user import requests.
      tags:
      - UserImport
      x-ds-methodname: getBulkUserImportRequests
      x-ds-method: getBulkUserImportRequests
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/{importId}:
    delete:
      description: |-
        Deletes a specific import request and its results.

        To delete a user, see [closeBulkUserImportRequest](/docs/admin-api/reference/bulkoperations/userimport/closebulkuserimportrequest/).

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationImport_OrganizationImportUsers_DeleteById
      security:
      - accessCode:
        - user_write
      summary: Deletes a specific user import request.
      tags:
      - UserImport
      x-ds-methodname: deleteBulkUserImport
      x-ds-method: deleteBulkUserImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
    get:
      description: |-
        Returns the details of a single user import request.

        Use this method to check the status of the request by looking at the `status` property of the response.
        Once the status becomes `completed` (or fails), use this method to get the details.

        To get a list of all of the user import requests, use `getBulkUserImportRequests`.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationImport_OrganizationImportUsers_GetById
      security:
      - accessCode:
        - user_read
      summary: Returns the details of a single user import request.
      tags:
      - UserImport
      x-ds-methodname: getBulkUserImportRequest
      x-ds-method: getBulkUserImportRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/{importId}/results_csv:
    get:
      description: |
        Returns the contents of the CSV file
        associated with a user import request.

        The results have an additional column,
        `ProcessingResults`,
        that describes the results of importing that row.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationImport_OrganizationImportUsers_GetCSVResults
      security:
      - accessCode:
        - user_read
      summary: |-
        Given the ID of a user import request,
        return the CSV file that was imported.
      tags:
      - UserImport
      x-ds-methodname: getBulkUserImportCSV
      x-ds-method: getBulkUserImportCSV
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/identity_providers:
    get:
      description: |-
        Returns the list of identity providers for an organization.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `identity_provider_read`.
      operationId: Organization_GetIdentityProviders
      security:
      - accessCode:
        - identity_provider_read
      summary: Returns the list of identity providers for an organization.
      tags:
      - IdentityProviders
      x-ds-methodname: getIdentityProviders
      x-ds-method: getIdentityProviders
      x-ds-service: IdentityProviders
      x-ds-in-sdk: true
  /v2/data_redaction/organizations/{organizationId}/user:
    post:
      description: "Deletes data for one or more of a user's account memberships.\n\
        \nTo call this endpoint: \n* You must be an organization administrator (or\
        \ delegated administrator) with permission to manage the specified accounts\
        \ or the user's email domain.\n* The user must have been closed for at least\
        \ 24 hours.\n\n**Note:** After a user's data is deleted for every account\
        \ to which they belong, their user-level data will automatically be deleted.\n\
        \n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_data_redact`."
      operationId: DataRedaction_RedactIndividualUserData
      security:
      - accessCode:
        - user_data_redact
      summary: Deletes data for one or more of a user's account memberships.
      tags:
      - DataDeletion
      x-ds-methodname: redactIndividualUserData
      x-ds-method: redactIndividualUserData
      x-ds-service: Organizations
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/reserved_domains:
    get:
      description: |-
        Returns the list of reserved domains for the organization.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `domain_read`.
      operationId: Organization_GetReservedDomains
      security:
      - accessCode:
        - domain_read
      summary: Returns the list of reserved domains for the organization.
      tags:
      - ReservedDomains
      x-ds-methodname: getReservedDomains
      x-ds-method: getReservedDomains
      x-ds-service: ReservedDomains
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/profiles:
    post:
      description: |-
        Updates a user's information.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: User_Users_UpdateV2
      security:
      - accessCode:
        - user_write
      summary: Updates a user's information.
      tags:
      - eSignUserManagement
      x-ds-methodname: updateUser
      x-ds-method: updateUser
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/email_addresses:
    post:
      description: |
        Updates a user's email address.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: User_Users_UpdateEmailAddressesV2
      security:
      - accessCode:
        - user_write
      summary: Updates a user's email address.
      tags:
      - Users
      x-ds-methodname: updateEmailAddress
      x-ds-method: updateEmailAddress
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/{userId}/accounts:
    delete:
      description: |-
        Closes a user's memberships.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.

        This method requires user authentication. It will fail with an [application access token](/docs/admin-api/admin101/application-auth/).
      operationId: User_Users_CloseMembershipsV2
      security:
      - accessCode:
        - user_write
      summary: Closes a user's memberships.
      tags:
      - eSignUserManagement
      x-ds-methodname: closeMemberships
      x-ds-method: closeMemberships
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users:
    get:
      description: |-
        Returns information about the users in an organization.

        You must include at least one of the following query parameters in the request:

        - `account_id`: The ID of an account associated with the organization.
        - `organization_reserved_domain_id`: The ID of one of the organization's reserved domains.
        - `email`: An email address associated with the users that you want to return.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationUser_OrganizationUsers_GetV2
      security:
      - accessCode:
        - user_read
      summary: Returns information about the users in an organization.
      tags:
      - Users
      x-ds-methodname: getUsers
      x-ds-method: getUsers
      x-ds-service: Users
      x-ds-in-sdk: true
    post:
      description: |
        Creates a new user.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationUser_Users_AddV2
      security:
      - accessCode:
        - user_write
      summary: Creates a new user.
      tags:
      - eSignUserManagement
      x-ds-methodname: createUser
      x-ds-method: createUser
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/{userId}/memberships/{membershipId}:
    post:
      description: |
        Activates user memberships.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationUser_Users_ActivateMembershipV2
      security:
      - accessCode:
        - user_write
      summary: Activates user memberships.
      tags:
      - eSignUserManagement
      x-ds-methodname: activateMembership
      x-ds-method: activateMembership
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/profile:
    get:
      description: |+
        Returns historical information about users with a specific email address.
        **Note:** The `email` query parameter is _required_.


        To get a list of users in an organization,
        use [Users: getUsers](/docs/admin-api/reference/usermanagement/users/getusers/)
        instead.

        For example, the following request gets information about
        accounts that use `max@example.net` as an email address:


        ```json
        GET /Management/v2/organizations/96e994fa-xxxx-xxxx-xxxx-c5fe9d1ccd10/users/profile?email=max@example.net

        {
          "users": [
            {
              "id": "6b67a1ee-xxxx-xxxx-xxxx-385763624163",
              "site_id": 1,
              "site_name": "Monadnock",
              "user_name": "Max Example",
              "first_name": "Max",
              "last_name": "Example",
              "user_status": "active",
              "default_account_id": "f636f297-xxxx-xxxx-xxxx-8e7a14715950",
              "default_account_name": "BizCo",
              "is_organization_admin": false,
              "created_on": "2019-04-01T22:11:56.457",
              "memberships": [
                {
                  "email": "max@example.net",
                  "account_id": "624e3e00-xxxx-xxxx-xxxx-43918c520dab",
                  "external_account_id": "17xxxxx1",
                  "account_name": "LoanCo",
                  "is_external_account": false,
                  "status": "active",
                  "permission_profile": { },
                  "created_on": "2019-04-01T22:11:56.457",
                  "groups": [ ],
                  "is_admin": false
                },
                {
                  "email": "max@example.net",
                  "account_id": "f636f297-xxxx-xxxx-xxxx-8e7a14715950",
                  "external_account_id": "25xxxxx0",
                  "account_name": "BizCo",
                  "is_external_account": true,
                  "status": "active",
                  "permission_profile": { },
                  "created_on": "2021-07-07T15:10:51.96",
                  "groups": [ ],
                  "is_admin": false
                },
                {
                  "email": "max@example.net",
                  "account_id": "6aed3a52-xxxx-xxxx-xxxx-e89988167cfd",
                  "external_account_id": "11xxxxx1",
                  "account_name": "SleepCo",
                  "is_external_account": true,
                  "status": "closed",
                  "permission_profile": { },
                  "created_on": "2021-07-11T12:40:44.26",
                  "groups": [],
                  "is_admin": true,
                  "closed_on": "2021-07-13T08:40:51.8"
                }
              ],
              "identities": [],
              "device_verification_enabled": false
            }
          ]
        }
        ```

        The response includes up to the first 20 users modified in the last 10 days.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.




      operationId: OrganizationUser_OrganizationUsers_GetProfileV2
      security:
      - accessCode:
        - user_read
      summary: |
        Returns historical information about users with a specific email address.
      tags:
      - eSignUserManagement
      x-ds-methodname: getUserProfiles
      x-ds-method: getUserProfiles
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/{userId}/identities:
    delete:
      description: |
        Deletes user identities.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationUser_DeleteIdentitiesV2
      security:
      - accessCode:
        - user_write
      summary: Deletes user identities.
      tags:
      - eSignUserManagement
      x-ds-methodname: deleteIdentities
      x-ds-method: deleteIdentities
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/users:
    post:
      description: |+
        Adds users to an account.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.

      operationId: OrganizationUser_OrganizationUsers_PostAccountUsersV2
      security:
      - accessCode:
        - user_write
      summary: Adds users to an account.
      tags:
      - eSignUserManagement
      x-ds-methodname: addUsers
      x-ds-method: addUsers
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups:
    get:
      description: |-
        Returns a list of DSGroups.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: DocuSignGroupsv21_GetDSGroups_V2_1
      security:
      - accessCode:
        - user_read
      summary: Returns a list of DSGroups.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: getDSGroups
      x-ds-method: getDSGroups
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    post:
      description: |-
        Creates a new DSGroup.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: DocuSignGroupsv21_AddDSGroup_V2_1
      security:
      - accessCode:
        - user_write
      summary: Creates a new DSGroup.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: addDSGroup
      x-ds-method: addDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}:
    delete:
      description: |-
        Deletes a DSGroup.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: DocuSignGroupsv21_DeleteDSGroup_V2_1
      security:
      - accessCode:
        - user_write
      summary: Deletes a DSGroup.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: deleteDSGroup
      x-ds-method: deleteDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    get:
      description: |-
        Returns details about a single DSGroup.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: DocuSignGroupsv21_GetDSGroup_V2_1
      security:
      - accessCode:
        - user_read
      summary: Returns details about a single DSGroup.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: getDSGroup
      x-ds-method: getDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}/users:
    delete:
      description: |-
        Removes a list of users from a DSGroup. In the request body, you can specify users by ID or email address. If both parameters are included, the email address parameter will be ignored.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: DocuSignGroupsv21_RemoveDSGroupUsers_V2_1
      security:
      - accessCode:
        - user_write
      summary: Removes a list of users from a DSGroup.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: removeDSGroupUsers
      x-ds-method: removeDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    get:
      description: |-
        Gets a list of users in a DSGroup.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: DocuSignGroupsv21_GetDSGroupUsers_V2_1
      security:
      - accessCode:
        - user_read
      summary: Gets a list of users in a DSGroup.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: getDSGroupUsers
      x-ds-method: getDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    post:
      description: |-
        Adds a list of users to a DSGroup.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: DocuSignGroupsv21_AddDSGroupUsers_V2_1
      security:
      - accessCode:
        - user_write
      summary: Adds a list of users to a DSGroup.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: addDSGroupUsers
      x-ds-method: addDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/products/permission_profiles:
    get:
      description: |-
        Gets products associated with the account and the available permission profiles.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationProductPermissionProfile_GetProductPermissionProfiles
      security:
      - accessCode:
        - user_read
      summary: Gets products associated with the account and the available permission
        profiles.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: getProductPermissionProfiles
      x-ds-method: getProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/products/users/{userId}/permission_profiles:
    get:
      description: |-
        Retrieves a list of a user's permission profiles for each account's product. The user is specified by the ID provided in the `userId` path parameter.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationProductPermissionProfile_GetUserProductPermissionProfiles
      security:
      - accessCode:
        - user_read
      summary: Retrieves a user's product permission profiles by user ID.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: getUserProductPermissionProfiles
      x-ds-method: getUserProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
    post:
      description: |-
        Sets permission profiles for one or more products for a given user. The user is specified by the `userId` path parameter.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationProductPermissionProfile_PostUserProductPermissionProfiles
      security:
      - accessCode:
        - user_write
      summary: Assigns permission profiles for a user by user ID.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: addUserProductPermissionProfiles
      x-ds-method: addUserProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/users:
    post:
      description: |-
        Creates and updates a multi-product user.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationUser_OrganizationUsers_PostAccountUsersV2_1
      security:
      - accessCode:
        - user_write
      summary: Creates and updates a multi-product user.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: addOrUpdateUser
      x-ds-method: addOrUpdateUser
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/users/dsprofile:
    get:
      description: |-
        Gets information about a user specified by the `email` query parameter.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationUser_OrganizationUsers_GetDSProfiles
      security:
      - accessCode:
        - user_read
      summary: Retrieves the DS profile for a user specified by email address.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: getUserDSProfilesByEmail
      x-ds-method: getUserDSProfilesByEmail
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/users/{userId}/dsprofile:
    get:
      description: |-
        Gets information about a user specified by the `userId` query parameter.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationUser_OrganizationUsers_GetDSProfileByUserId
      security:
      - accessCode:
        - user_read
      summary: Retrieves the DS profile for a user specified by ID.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: getUserDSProfile
      x-ds-method: getUserDSProfile
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/products/users:
    delete:
      description: |-
        Revokes a specified user's access to one or more products.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationProductPermissionProfile_RemoveUserProducts
      security:
      - accessCode:
        - user_write
      summary: Revokes a user's access to one or more products.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: removeUserProductPermission
      x-ds-method: removeUserProductPermission
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/products/permission_profiles/users:
    get:
      description: |-
        Retrieves a list of a user's permission profiles for each account's product. The user is specified by the email address provided in the `email` query parameter.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.
      operationId: OrganizationProductPermissionProfile_GetUserProductPermissionProfilesByEmail
      security:
      - accessCode:
        - user_write
      summary: Retrieves a user's product permission profiles by email address.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: getUserProductPermissionProfilesByEmail
      x-ds-method: getUserProductPermissionProfilesByEmail
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
    post:
      description: |-
        Sets permission profiles for one or more products for a given user. The user is specified by the `email` property in the request body.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.
      operationId: OrganizationProductPermissionProfile_PostUserProductPermissionProfilesByEmail
      security:
      - accessCode:
        - user_write
      summary: Assigns permission profiles for a user by email address.
      tags:
      - MultiProductUserManagement
      x-ds-methodname: addUserProductPermissionProfilesByEmail
      x-ds-method: addUserProductPermissionProfilesByEmail
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
  /v1/organizations/{organizationId}/assetGroups/accounts:
    get:
      description: |-
        Returns a list of asset group accounts for an organization.

        An asset group is a set of modules, products, plans, and charges purchased for your organization. An asset group account is an account that has been linked to an asset group.

        To call this endpoint:
        * You must be an administrator for the specified organization.

        [Required authentication scopes](/docs/admin-api/admin101/auth/): `asset_group_account_read`.
      operationId: OrganizationProvisionAssetGroup_GetAssetGroupAccountsByOrg
      security:
      - accessCode:
        - asset_group_account_read
      summary: Get asset group accounts for an organization.
      tags:
      - AccountCloning
      x-ds-methodname: getAssetGroupAccounts
      x-ds-method: getAssetGroupAccounts
      x-ds-service: ProvisionAssetGroup
      x-ds-in-sdk: true
  /v1/organizations/{organizationId}/assetGroups/accountClone:
    post:
      description: "Clones an existing DocuSign account. Cloning an account copies\
        \ the plan items and eSignature settings. Users, templates, and permission\
        \ profiles are _not_ copied into the target account. The new account will\
        \ linked to the same organization.\n\nIn the request body, specify the source\
        \ account you are cloning by its ID. You can get the IDs for your organization's\
        \ asset group accounts using the [getAssetGroupAccounts](/docs/admin-api/reference/accountprovisioning/accountcloning/getassetgroupaccounts/)\
        \ endpoint. \n\nYou also need to specify information about the new target\
        \ account, including the name, location, and administrator. To set the location,\
        \ provide either the `countryCode` or `region` properties. (If both are specified,\
        \ the `region` value will be used.)\n\nThe request body looks like this:\n\
        ```\n{\n    \"sourceAccount\": {\n        \"id\": \"624e3e00-xxxx-xxxx-xxxx-43918c520dab\"\
        \n    },\n    \"targetAccount\": {\n        \"name\": \"My Cloned Account\"\
        ,\n        \"admin\": {\n            \"firstName\": \"Francis\",\n       \
        \     \"lastName\": \"Beagle\",\n            \"email\": \"francis@example.com\"\
        \n        },\n        \"region\": \"NA\"\n    }\n}\n```\n\nTo call this endpoint:\n\
        * You must be an administrator for the specified organization.\n* The source\
        \ account must be on the same plan as your contract.\n* The source account\
        \ must be an asset group account. An asset group is a set of modules, products,\
        \ plans, and charges purchased for your organization. An asset group account\
        \ is an account that has been linked to an asset group.\n\n[Required scopes](/docs/admin-api/admin101/auth/):\
        \ `asset_group_account_clone_write`."
      operationId: OrganizationProvisionAssetGroup_CloneAssetGroupAccount
      security:
      - accessCode:
        - asset_group_account_clone_write
      summary: Clone an existing DocuSign account.
      tags:
      - AccountCloning
      x-ds-methodname: cloneAssetGroupAccount
      x-ds-method: cloneAssetGroupAccount
      x-ds-service: ProvisionAssetGroup
      x-ds-in-sdk: true
  /v1/organizations/{organizationId}/assetGroups/accountClones:
    get:
      description: |-
        Retrieves all the cloned accounts for an organization.

        To call this endpoint:
        * You must be an administrator for the specified organization.

        [Required scopes](/docs/admin-api/admin101/auth/): `asset_group_account_clone_read`.
      operationId: OrganizationProvisionAssetGroup_GetAssetGroupAccountClonesByOrgId
      security:
      - accessCode:
        - asset_group_account_clone_read
      summary: Gets all asset group account clones for an organization.
      tags:
      - AccountCloning
      x-ds-methodname: getAssetGroupAccountClonesByOrgId
      x-ds-method: getAssetGroupAccountClonesByOrgId
      x-ds-service: ProvisionAssetGroup
      x-ds-in-sdk: true
  /v1/organizations/{organizationId}/assetGroups/{assetGroupId}/accountClones/{assetGroupWorkId}:
    get:
      description: |-
        Gets information about a cloned account by the `assetGroupWorkId`.

        To call this endpoint:
        * You must be an administrator for the specified organization.

        [Required scopes](/docs/admin-api/admin101/auth/): `asset_group_account_clone_read`.
      operationId: OrganizationProvisionAssetGroup_GetAssetGroupAccountClone
      security:
      - accessCode:
        - asset_group_account_clone_read
      summary: Gets information about a single cloned account.
      tags:
      - AccountCloning
      x-ds-methodname: getAssetGroupAccountClone
      x-ds-method: getAssetGroupAccountClone
      x-ds-service: ProvisionAssetGroup
      x-ds-in-sdk: true
components:
  securitySchemes:
    accessCode:
      description: OAuth2 Access code Grant
      flows:
        authorizationCode:
          authorizationUrl: https://account.docusign.com/oauth/auth
          scopes:
            organization_read: ""
            user_data_redact: ""
            permission_read: ""
            group_read: ""
            user_read: ""
            account_read: ""
            account_write: ""
            user_write: ""
            identity_provider_read: ""
            domain_read: ""
          tokenUrl: https://account.docusign.com/oauth/auth
      type: oauth2
x-ds-categories:
- name: IdentityProviders
  summary: Methods to get a list of identity providers.
  description: Methods to get a list of identity providers.
- name: ReservedDomains
  summary: Methods to get a list of reserved domains.
  description: Methods to get a list of reserved domains.
- name: UserManagement
  summary: Methods to manage users in an account.
  description: Methods to manage users in an account.
- name: BulkOperations
  summary: Methods to import and export users and accounts.
  description: Methods to import and export users and accounts.
- name: Organization
  summary: Methods for working with organizations.
  description: Methods for working with organizations.
- name: AccountProvisioning
  summary: Methods to provision accounts in your organization.
  description: Methods to provision accounts in your organization.
x-original-swagger-version: "2.0"
