/*
DocuSign REST API

The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

API version: v2.1
Contact: devcenter@docusign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BulkSendResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkSendResponse{}

// BulkSendResponse The object contains the response to a bulk send request.
type BulkSendResponse struct {
	// A batch identifier that you can use to get the status of the batch.
	BatchId *string `json:"batchId,omitempty"`
	// 
	BatchName *string `json:"batchName,omitempty"`
	// The total number of items in the batch being queried.
	BatchSize *string `json:"batchSize,omitempty"`
	// The GUID of the envelope or template that was sent.
	EnvelopeOrTemplateId *string `json:"envelopeOrTemplateId,omitempty"`
	// A human-readable object that describes errors that occur. It is only valid for responses and ignored in requests.
	ErrorDetails []string `json:"errorDetails,omitempty"`
	// A list of errors that occurred. This information is intended to be parsed by machine.
	Errors []string `json:"errors,omitempty"`
	// 
	QueueLimit *string `json:"queueLimit,omitempty"`
	// 
	TotalQueued *string `json:"totalQueued,omitempty"`
}

// NewBulkSendResponse instantiates a new BulkSendResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkSendResponse() *BulkSendResponse {
	this := BulkSendResponse{}
	return &this
}

// NewBulkSendResponseWithDefaults instantiates a new BulkSendResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkSendResponseWithDefaults() *BulkSendResponse {
	this := BulkSendResponse{}
	return &this
}

// GetBatchId returns the BatchId field value if set, zero value otherwise.
func (o *BulkSendResponse) GetBatchId() string {
	if o == nil || IsNil(o.BatchId) {
		var ret string
		return ret
	}
	return *o.BatchId
}

// GetBatchIdOk returns a tuple with the BatchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendResponse) GetBatchIdOk() (*string, bool) {
	if o == nil || IsNil(o.BatchId) {
		return nil, false
	}
	return o.BatchId, true
}

// HasBatchId returns a boolean if a field has been set.
func (o *BulkSendResponse) HasBatchId() bool {
	if o != nil && !IsNil(o.BatchId) {
		return true
	}

	return false
}

// SetBatchId gets a reference to the given string and assigns it to the BatchId field.
func (o *BulkSendResponse) SetBatchId(v string) {
	o.BatchId = &v
}

// GetBatchName returns the BatchName field value if set, zero value otherwise.
func (o *BulkSendResponse) GetBatchName() string {
	if o == nil || IsNil(o.BatchName) {
		var ret string
		return ret
	}
	return *o.BatchName
}

// GetBatchNameOk returns a tuple with the BatchName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendResponse) GetBatchNameOk() (*string, bool) {
	if o == nil || IsNil(o.BatchName) {
		return nil, false
	}
	return o.BatchName, true
}

// HasBatchName returns a boolean if a field has been set.
func (o *BulkSendResponse) HasBatchName() bool {
	if o != nil && !IsNil(o.BatchName) {
		return true
	}

	return false
}

// SetBatchName gets a reference to the given string and assigns it to the BatchName field.
func (o *BulkSendResponse) SetBatchName(v string) {
	o.BatchName = &v
}

// GetBatchSize returns the BatchSize field value if set, zero value otherwise.
func (o *BulkSendResponse) GetBatchSize() string {
	if o == nil || IsNil(o.BatchSize) {
		var ret string
		return ret
	}
	return *o.BatchSize
}

// GetBatchSizeOk returns a tuple with the BatchSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendResponse) GetBatchSizeOk() (*string, bool) {
	if o == nil || IsNil(o.BatchSize) {
		return nil, false
	}
	return o.BatchSize, true
}

// HasBatchSize returns a boolean if a field has been set.
func (o *BulkSendResponse) HasBatchSize() bool {
	if o != nil && !IsNil(o.BatchSize) {
		return true
	}

	return false
}

// SetBatchSize gets a reference to the given string and assigns it to the BatchSize field.
func (o *BulkSendResponse) SetBatchSize(v string) {
	o.BatchSize = &v
}

// GetEnvelopeOrTemplateId returns the EnvelopeOrTemplateId field value if set, zero value otherwise.
func (o *BulkSendResponse) GetEnvelopeOrTemplateId() string {
	if o == nil || IsNil(o.EnvelopeOrTemplateId) {
		var ret string
		return ret
	}
	return *o.EnvelopeOrTemplateId
}

// GetEnvelopeOrTemplateIdOk returns a tuple with the EnvelopeOrTemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendResponse) GetEnvelopeOrTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.EnvelopeOrTemplateId) {
		return nil, false
	}
	return o.EnvelopeOrTemplateId, true
}

// HasEnvelopeOrTemplateId returns a boolean if a field has been set.
func (o *BulkSendResponse) HasEnvelopeOrTemplateId() bool {
	if o != nil && !IsNil(o.EnvelopeOrTemplateId) {
		return true
	}

	return false
}

// SetEnvelopeOrTemplateId gets a reference to the given string and assigns it to the EnvelopeOrTemplateId field.
func (o *BulkSendResponse) SetEnvelopeOrTemplateId(v string) {
	o.EnvelopeOrTemplateId = &v
}

// GetErrorDetails returns the ErrorDetails field value if set, zero value otherwise.
func (o *BulkSendResponse) GetErrorDetails() []string {
	if o == nil || IsNil(o.ErrorDetails) {
		var ret []string
		return ret
	}
	return o.ErrorDetails
}

// GetErrorDetailsOk returns a tuple with the ErrorDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendResponse) GetErrorDetailsOk() ([]string, bool) {
	if o == nil || IsNil(o.ErrorDetails) {
		return nil, false
	}
	return o.ErrorDetails, true
}

// HasErrorDetails returns a boolean if a field has been set.
func (o *BulkSendResponse) HasErrorDetails() bool {
	if o != nil && !IsNil(o.ErrorDetails) {
		return true
	}

	return false
}

// SetErrorDetails gets a reference to the given []string and assigns it to the ErrorDetails field.
func (o *BulkSendResponse) SetErrorDetails(v []string) {
	o.ErrorDetails = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *BulkSendResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *BulkSendResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *BulkSendResponse) SetErrors(v []string) {
	o.Errors = v
}

// GetQueueLimit returns the QueueLimit field value if set, zero value otherwise.
func (o *BulkSendResponse) GetQueueLimit() string {
	if o == nil || IsNil(o.QueueLimit) {
		var ret string
		return ret
	}
	return *o.QueueLimit
}

// GetQueueLimitOk returns a tuple with the QueueLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendResponse) GetQueueLimitOk() (*string, bool) {
	if o == nil || IsNil(o.QueueLimit) {
		return nil, false
	}
	return o.QueueLimit, true
}

// HasQueueLimit returns a boolean if a field has been set.
func (o *BulkSendResponse) HasQueueLimit() bool {
	if o != nil && !IsNil(o.QueueLimit) {
		return true
	}

	return false
}

// SetQueueLimit gets a reference to the given string and assigns it to the QueueLimit field.
func (o *BulkSendResponse) SetQueueLimit(v string) {
	o.QueueLimit = &v
}

// GetTotalQueued returns the TotalQueued field value if set, zero value otherwise.
func (o *BulkSendResponse) GetTotalQueued() string {
	if o == nil || IsNil(o.TotalQueued) {
		var ret string
		return ret
	}
	return *o.TotalQueued
}

// GetTotalQueuedOk returns a tuple with the TotalQueued field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendResponse) GetTotalQueuedOk() (*string, bool) {
	if o == nil || IsNil(o.TotalQueued) {
		return nil, false
	}
	return o.TotalQueued, true
}

// HasTotalQueued returns a boolean if a field has been set.
func (o *BulkSendResponse) HasTotalQueued() bool {
	if o != nil && !IsNil(o.TotalQueued) {
		return true
	}

	return false
}

// SetTotalQueued gets a reference to the given string and assigns it to the TotalQueued field.
func (o *BulkSendResponse) SetTotalQueued(v string) {
	o.TotalQueued = &v
}

func (o BulkSendResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkSendResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BatchId) {
		toSerialize["batchId"] = o.BatchId
	}
	if !IsNil(o.BatchName) {
		toSerialize["batchName"] = o.BatchName
	}
	if !IsNil(o.BatchSize) {
		toSerialize["batchSize"] = o.BatchSize
	}
	if !IsNil(o.EnvelopeOrTemplateId) {
		toSerialize["envelopeOrTemplateId"] = o.EnvelopeOrTemplateId
	}
	if !IsNil(o.ErrorDetails) {
		toSerialize["errorDetails"] = o.ErrorDetails
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.QueueLimit) {
		toSerialize["queueLimit"] = o.QueueLimit
	}
	if !IsNil(o.TotalQueued) {
		toSerialize["totalQueued"] = o.TotalQueued
	}
	return toSerialize, nil
}

type NullableBulkSendResponse struct {
	value *BulkSendResponse
	isSet bool
}

func (v NullableBulkSendResponse) Get() *BulkSendResponse {
	return v.value
}

func (v *NullableBulkSendResponse) Set(val *BulkSendResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkSendResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkSendResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkSendResponse(val *BulkSendResponse) *NullableBulkSendResponse {
	return &NullableBulkSendResponse{value: val, isSet: true}
}

func (v NullableBulkSendResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkSendResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


